/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustSafetyRouteImport } from './routes/trust-safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PressRouteImport } from './routes/press'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIndexRouteImport } from './routes/tutors/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as TutorsTutorIdRouteImport } from './routes/tutors/$tutorId'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs/$blogId'

const TrustSafetyRoute = TrustSafetyRouteImport.update({
  id: '/trust-safety',
  path: '/trust-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIndexRoute = TutorsIndexRouteImport.update({
  id: '/tutors/',
  path: '/tutors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsTutorIdRoute = TutorsTutorIdRouteImport.update({
  id: '/tutors/$tutorId',
  path: '/tutors/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/mobile-app': typeof MobileAppRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/tutors/': typeof TutorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/mobile-app': typeof MobileAppRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/blogs': typeof BlogsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/tutors': typeof TutorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/mobile-app': typeof MobileAppRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/trust-safety': typeof TrustSafetyRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/blogs/': typeof BlogsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/tutors/': typeof TutorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/help-center'
    | '/login'
    | '/mobile-app'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/blogs/$blogId'
    | '/subjects/$subjectId'
    | '/tutors/$tutorId'
    | '/blogs/'
    | '/subjects/'
    | '/tutors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/help-center'
    | '/login'
    | '/mobile-app'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/blogs/$blogId'
    | '/subjects/$subjectId'
    | '/tutors/$tutorId'
    | '/blogs'
    | '/subjects'
    | '/tutors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/help-center'
    | '/login'
    | '/mobile-app'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/trust-safety'
    | '/blogs/$blogId'
    | '/subjects/$subjectId'
    | '/tutors/$tutorId'
    | '/blogs/'
    | '/subjects/'
    | '/tutors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CareersRoute: typeof CareersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HelpCenterRoute: typeof HelpCenterRoute
  LoginRoute: typeof LoginRoute
  MobileAppRoute: typeof MobileAppRoute
  PressRoute: typeof PressRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrustSafetyRoute: typeof TrustSafetyRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  TutorsTutorIdRoute: typeof TutorsTutorIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  TutorsIndexRoute: typeof TutorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-safety': {
      id: '/trust-safety'
      path: '/trust-safety'
      fullPath: '/trust-safety'
      preLoaderRoute: typeof TrustSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/': {
      id: '/tutors/'
      path: '/tutors'
      fullPath: '/tutors/'
      preLoaderRoute: typeof TutorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$tutorId': {
      id: '/tutors/$tutorId'
      path: '/tutors/$tutorId'
      fullPath: '/tutors/$tutorId'
      preLoaderRoute: typeof TutorsTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CareersRoute: CareersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HelpCenterRoute: HelpCenterRoute,
  LoginRoute: LoginRoute,
  MobileAppRoute: MobileAppRoute,
  PressRoute: PressRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrustSafetyRoute: TrustSafetyRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  TutorsTutorIdRoute: TutorsTutorIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  TutorsIndexRoute: TutorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
